version: 2.1

executors:
  hadolint:
    description: Hadolint Docker image
    docker:
      - image: 'hadolint/hadolint:<<parameters.tag>>'
    parameters:
      resource-class:
        default: small
        enum:
          - small
          - medium
          - medium+
          - large
          - xlarge
        type: enum
      tag:
        default: latest-debian
        description: >
          Specific Hadolint image (make sure to use a `debian` tag, otherwise image
          will not be usable on CircleCI):
          https://hub.docker.com/r/hadolint/hadolint/tags
        type: string
    resource_class: <<parameters.resource-class>>

jobs:
  hellolint:
    parameters:
      version:
        default: latest-debian
        description: >
          Specific Hadolint image (make sure to use a `debian` tag, otherwise image
          will not be usable on CircleCI):
          https://hub.docker.com/r/hadolint/hadolint/tags
        type: string

      executor-class:
        description: Resource class for the Hadolint executor
        default: small
        enum:
          - small
          - medium
          - medium+
          - large
          - xlarge
        type: enum

    executor:
      name: hadolint
      tag: << parameters.version >>
      resource-class: << parameters.executor-class >>
     
    steps:
      - run: hadolint --version
          
workflows:
  welcome:
    jobs:
      - hellolint:
          version: 2.2.0-debian
