version: 2.1

jobs:
  bloop:
    docker:
      - image: ebizmarts/magento2-php73:0.0.4
#       - image: circleci/php
        environment:
          PHP_VERSION: 7.3
    steps:
      - run: sudo apt --version
      - run: sudo apt update apt
      - run: sudo apt upgrade apt
      - run: sudo apt --version
      - run: sudo apt-get update
      - run: sudo apt-get --version
      - run: sudo apt-get upgrade
      - run: sudo apt-get --version
      - run: sudo apt-get install apt-transport-https      
          
workflows:
  welcome:
    jobs:
      - bloop

