version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - run: ./script.sh
      - run:
          name: I test I test
          command: |
              source $BASH_ENV
              echo $plan_diff
              echo $FILE
              echo $MESSAGE
      
  setup-windows:
    executor:
      name: windows/default
      shell: bash.exe
    steps:
      - run: git version
          
workflows:
  build-deploy:
    jobs:
      - setup
#       - setup-windows
