version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          command: |
              chmod +x ./script.sh
              ./script.sh
      - run:
          name: I test I test
          command: |
              source $BASH_ENV
              echo $plan_diff
              echo $FILE
              echo $MESSAGE
          
workflows:
  build-deploy:
    jobs:
      - setup
