version: 2.1

setup: true
 
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  init:
    executor: continuation/default
    steps:
      - checkout
      - run: echo $DOCKER_VERSION
      - continuation/continue:
          parameters: '{"lacondition": "$condition_needed"}'
          configuration_path: .circleci/local.yml
        
workflows:
  setup:
    jobs:
      - init
