version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - run:
          command: |
            type=$(uname -s | tr '[:upper:]' '[:lower:]')
            echo "export family=$(echo $type)" >> BASH_ENV
      - run:
          shell: bash.exe
          command: |
            type=$(uname -s | tr '[:upper:]' '[:lower:]')
            echo "export family=$(echo $type)" >> BASH_ENV
          when: on_fail
      - run:
          command: |
            case $family in
              linux)
                osID=$(grep -e "^ID=" /etc/os-release | cut -c4-)
                ;;
              darwin)
                osID=macos
                ;;
              msys_nt*)
                osID=$(systeminfo|grep "^OS Name"|awk -F':' '{print $2}'|awk '{$1=""; print}')
                ;;
              *)
                echo "Unsupported operating system."
                exit 1
                ;;
            esac

            case $osID in
              *Windows*)
                osVersion=$(systeminfo|grep "^OS Version"|awk -F':' '{print $2}'|awk -F' ' '{print $1}')
                ;;
            esac

            echo "export OS_VERSION=$(echo $osVersion)" >> $BASH_ENV
            echo "export OS_ID=$(printf %s${osID})" >> $BASH_ENV

            echo $osVersion
            echo $osID



            if [[ $EUID -ne 0 ]]; then
              SUDO=sudo
            fi
            command -v sudo >/dev/null 2>&1 || { SUDO=""; }

      - run: |
          echo OS is "$OS_ID"
          echo Version is "$OS_VERSION"
          case $OS_ID in
              *2019*)
                echo "WIIIIIIIIIIIIIIIN DOES"
                ;;
          esac

workflows:
  whatos:
    jobs:
      - build
