version: 2.1

executors:
    hadolint:
        description: Hadolint Docker image
        docker:
            - image: hadolint/hadolint:<<parameters.tag>>
        parameters:
            resource-class:
                default: small
                enum:
                    - small
                    - medium
                    - medium+
                    - large
                    - xlarge
                type: enum
            tag:
                default: latest-debian
                description: |
                    Specific Hadolint image (make sure to use a `debian` tag, otherwise image will not be usable on CircleCI): https://hub.docker.com/r/hadolint/hadolint/tags
                type: string
        resource_class: <<parameters.resource-class>>

jobs:
  hadolint:
    executor: hadolint
      resource-class: medium
      tag: 2.4.1-debian
      
  steps:
    - run: echo "Hadoooooooooooo Lint"
          
workflows:
  welcome:
    jobs:
      - bloop

