version: 2.1

jobs:
  setup:
    docker:
      - image: circleci/python
      
    environment:
      FOO: bar
      
    steps:
      - setup_remote_docker:
          version: 19.03.13
          
      - run: |
          ssh remote-docker \<<EOF
            sudo bash -c 'echo $bar'
            echo $bar
            sudo docker info
          EOF
          
          
workflows:
  build-deploy:
    jobs:
     - setup
      
