version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    command: sh -c "echo ${<<parameters.ARG>>}; sh -c env
    parameters:
      ARG:
        type: env_var_name
        default: foo
    environment:
      FOO: $foo
   
    steps:
      - run: sh -c env
      
workflows:
  build-deploy:
    jobs:
      - setup
