version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    parameters:
      ARG:
        type: env_var_name
        default: foo
    environment:
      FOO: ${<<parameters.ARG>>}
   
    steps:
      - run: sh -c env
      - run: echo ${<<parameters.ARG>>}
      
workflows:
  build-deploy:
    jobs:
      - setup
