version: 2.1
  
jobs:
  setup:
    docker:
      - image: circleci/node
    steps:
      - run: |
          mkdir /home/circleci/project/tmp
          echo "Hello file" > /home/circleci/project/tmp/toto.txt
          pwd
          ls -al
          ls -al /home/circleci/project/tmp
      - persist_to_workspace:
          root: tmp
          paths:
            - toto.txt
  space:
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: cat ~/tmp/toto.txt
      
          
workflows:
  build-deploy:
    jobs:
      - setup
      - space:
          requires:
            - setup
