version: 2.1

setup: true
 
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  init:
    executor: continuation/default
    steps:
      - checkout
      - run: export DOCKER_VERSION >> BASH_ENV
      - continuation/continue:
          configuration_path: .circleci/local.yml
        
workflows:
  setup:
    jobs:
      - init
