version: 2.1
  
orbs:
  docker: circleci/docker@1.5.0
  
jobs:
  setup:
    docker:
      - image: circleci/node

    steps:
      - docker/install-docker:
          version: $DOCKER_VERSION
      - setup_remote_docker:
          version: ${!DOCKER_VERSION}
          
workflows:
  build-deploy:
    jobs:
      - setup
