version: 2.1

commands:
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run:
          name: Greetings
          command: echo "Hello << parameters.to >>"

jobs:
  sayhello: # defines a parameterized job
    description: A job that does very little other than demonstrate what a parameterized job looks like
    parameters:
      saywhat:
        description: "To whom shall we say hello?"
        default: "World"
        type: string
    docker:
      - image: circleci/node
    steps:
      - run: echo "Hello << parameters.saywhat >>"
      
          
workflows:
  welcome:
    jobs:
#       - messer
      - sayhello:
          saywhat: $MAVEN_COMMAND
          pre-steps:
            - when:
                condition:
                  equal: [ lacondition, << pipeline.git.branch >> ]
                steps:
                  - run: echo 'export MAVEN_COMMAND=deploy' >> $BASH_ENV

            
            - unless:
                condition:
                  equal: [ lacondition, << pipeline.git.branch >> ]
                steps:
                  - run: echo 'export MAVEN_COMMAND=package' >> $BASH_ENV

