version: 2.1

commands:
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run:
          name: Greetings
          command: echo "Hello << parameters.to >>"

jobs:
  sayhello: # defines a parameterized job
    description: A job that does very little other than demonstrate what a parameterized job looks like
    parameters:
      saywhat:
        description: "To whom shall we say hello?"
        default: "World"
        type: string
    docker:
      - image: circleci/node
    steps:
      - run: echo "Hello << parameters.saywhat >>"
      
      
#   messer:
#     parameters:
#       maven-command:
#         description: Package or Deeploy?
#         type: env_var_name
#         default: PACDEP

#     docker:
#       - image: circleci/node
#     steps:    
#       - when:
#           condition:
#             equal: [ master, << pipeline.git.branch >> ]
#           steps:
#             - run: echo 'export PACDEP="deploy"' >> $BASH_ENV
            
#       - unless:
#           condition:
#             equal: [ master, << pipeline.git.branch >> ]
#           steps:
#             - run: echo 'export PACDEP="package"' >> $BASH_ENV
              
#       - greeting:
#           to: ${<< parameters.maven-command >>}
          
workflows:
  welcome:
    jobs:
#       - messer
      - sayhello:
          saywhat: $MAVEN-COMMAN
          pre-steps:
            - when:
                condition:
                  equal: [ master, << pipeline.git.branch >> ]
                steps:
                  - run: echo 'export MAVEN-COMMAND=deploy' >> $BASH_ENV
            
            - unless:
                condition:
                  equal: [ master, << pipeline.git.branch >> ]
                steps:
                  - run: echo 'echo MAVEN-COMMAN=package' >> $BASH_ENV
