version: 2.1

jobs:
  bloop:
    docker:
      - image: ebizmarts/magento2-php73:0.0.4
#         - image: circleci/php
          environment:
            PHP_VERSION: 7.3
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https
      - run: sudo apt --version
      
          
workflows:
  welcome:
    jobs:
      - bloop

