version: 2.1

jobs:
  bloop:
    docker:
#       - image: ebizmarts/magento2-php73:0.0.4
      - image: circleci/php
        environment:
          PHP_VERSION: 7.3
    steps:
#       - run: sudo apt-get update && sudo apt-get install lsb-core
#       - run: lsb_release -a
#       - run: sudo sed -i '2,2s/buster/buster*/' /etc/apt/preferences.d/argon2-buster
      - run: sudo apt-show-versions apt-transport-https 
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https
      - run: sudo apt-show-versions apt-transport-https 
          
workflows:
  welcome:
    jobs:
      - bloop

